### ISSUE TITLE
EigenIntegration missing configure.h file

### ISSUE THREAD

**Issue by patricksafritpaz** [mosra/magnum-integration#117] opened 2024-12-27 16:26 UTC
I noticed, between commit 697ddd2cccf17aa03987da9a2213af99cd6d4cd3 and commit bc056f8800c88e21990e11461f75d409748f18a7 that building my project (that uses MagnumIntegration with Eigen and ImGui) that the CMake configuration began failing. I'm on Windows, using CMake with vcpkg. 

The error I first noticed was the "MagnumIntegration must be built with Eigen" coming from Cmake, I assume because 
`set(MagnumIntegration_${_component}_FOUND TRUE)` never got hit for Eigen in `FindMagnumIntegration.cmake`.

My best idea of the root cause is: [`configure.h` files are now required for each component](https://github.com/mosra/magnum-integration/commit/73d290f44dbf14d69f79cd044200fcbff9af445c#diff-f385900e6ffd215b636a82715062047937bca55cfc6cecf1b7cbe8c9253150bdR234), and currently the `include/Magnum/EigenIntegration` directory doesn't have one? I copied `configure.h` from the ImguiIntegration directory and did a find+replace of the three instances of IMGUI to EIGEN and it's working with that change.

**Comment by mosra** [comment] 2024-12-31 12:53
Whoops, sorry about this. Insufficient testing on my side, caused by the changes in 73d290f44dbf14d69f79cd044200fcbff9af445c. Should be fixed as of 90ec8cedff8a8f6eb8c6e1fc5b2e7d05e95c4db6.

**Closed by mosra** 2024-12-31 12:53 UTC
Labels: changelog mention added
